---
# Source: multi-demo/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: multi-demo-config
data:
  config-version: "v1"
  feature-flag: "true"
  log-level: "debug"
  max-connections: "50"
